version: '2'

services:

  mysql:
    environment:
      MYSQL_DATABASE: private_url_shortener
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: admin
    image: mysql

  private_url_shortener:
    extends:
      file: docker-compose.base.yml
      service: private_url_shortener
    environment:
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: mysql
      DATABASE_NAME: private_url_shortener
      DATABASE_PASSWORD: 12345
      DATABASE_USER: admin
    links:
      - mysql
