version: '2'

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  private_url_shortener:
    # build: ../
    image: jhmaddox/private_url_shortener
    environment:
      PRIVATE_SHORTENER_API_SECRET_KEY: __CHANGE_ME_ALSO__
      PRIVATE_SHORTENER_SIG_LENGTH: 8
      SECRET_KEY: __CHANGE_ME__
      STATIC_ROOT: /static_root/static
    volumes:
      - /static_root/static
